sonar.projectKey=LibraryHub
sonar.projectName=LibraryHub
sonar.projectVersion=1.0

sonar.sources=Backend/src,Backend/models,Frontend/src
sonar.tests=Backend/tests

sonar.exclusions=**/node_modules/**,Backend/coverage/**,Backend/python-service/**,Backend/migrations/**,Frontend/dist/**

sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=Frontend/src/**,Backend/models/**,Backend/src/config/**,Backend/src/routes/**,Backend/src/server.js,Backend/src/app.js,Backend/src/controllers/recommendationController.js